"""The desktop mega menu must be the taxonomy, exactly.

The panels used to be scraped out of the design handoff HTML, so the desktop
nav was the one surface that could disagree with taxonomy.json without
anything noticing: the mobile drawer, the breadcrumbs and the category chips
were all generated from it, the mega menu was not. gen_mega.py reads the
taxonomy now, and this asserts the result - every department, every group, every
leaf, in taxonomy order, linking to a collection that exists - so a future edit
to the generated file, or a hand-patch of the snippet, fails the build.

Also guards the dependency itself: a generator that reaches for the design
file or a browser again is a generator that can drift again.
"""
import json
import os
import re
import sys
import unicodedata

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT = os.path.dirname(HERE)

res = []
def ck(name, got, want=True): res.append((got == want, name, got))


def handleize(s):
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode()
    s = s.lower().replace('&', ' ').replace("'", '')
    return re.sub(r'-{2,}', '-', re.sub(r'[^a-z0-9]+', '-', s)).strip('-')


unesc = lambda s: s.replace('&amp;', '&')
theme = lambda *p: open(os.path.join(ROOT, 'shopify-theme', *p)).read()

taxonomy = {handleize(m['menu']): m for m in json.load(open(os.path.join(HERE, 'taxonomy.json')))}
handles = {c['handle'] for c in json.load(open(os.path.join(HERE, 'collections.json')))}
MEGA = theme('snippets', 'mega-menu.liquid')

# the eight departments, in the order the header and the homepage row use
depts = re.sub(r'{%-?\s*comment\s*-?%}.*?{%-?\s*endcomment\s*-?%}', '', theme('snippets', 'departments.liquid'), flags=re.S)
nav = [row.split('~')[1] for row in depts.strip().split('|')]

panels = {}
for m in re.finditer(r'<div class="mega-panel" data-mega-panel="([^"]+)">', MEGA):
    seg = MEGA[m.end():]
    nxt = seg.find('<div class="mega-panel"')
    panels[m.group(1)] = seg[:nxt if nxt > 0 else len(seg)]

ck('every nav department has a panel, in nav order', list(panels), nav)

link_re = re.compile(r'<a href="([^"]+)"[^>]*>([^<]*)</a>')
group_re = re.compile(r'<div class="mega-group">\s*<a href="([^"]+)"[^>]*>([^<]*)</a>(.*?)(?=<div class="mega-group">|\Z)', re.S)

for key, body in panels.items():
    menu = taxonomy.get(key)
    ck(f'{key}: is a taxonomy department', menu is not None)
    if not menu:
        continue
    groups, flat = menu.get('groups', []), menu.get('flat', [])
    found = group_re.findall(body)
    if groups and found:
        # a panel built from group headings: headings and their leaves, in order
        ck(f'{key}: groups match the taxonomy, in order',
           [unesc(t) for _, t, _ in found], [g['title'] for g in groups])
        ck(f'{key}: group links match their titles',
           [h for h, _, _ in found], ['/collections/' + handleize(g['title']) for g in groups])
        for (_, title, rest), g in zip(found, groups):
            ck(f"{key}: '{unesc(title)}' leaves match the taxonomy, in order",
               [unesc(t) for _, t in link_re.findall(rest)], g['items'])
    else:
        # a flat panel: every leaf once, in taxonomy order
        want = flat or [g['title'] for g in groups]
        ck(f'{key}: links are the taxonomy leaves, in order',
           [unesc(t) for _, t in link_re.findall(body)], want)

    for href, text in link_re.findall(body):
        h = href.replace('/collections/', '').strip('/')
        ck(f"{key}: '{unesc(text)}' -> {href} is a real collection", h in handles)
        ck(f"{key}: '{unesc(text)}' links to its own handle", h, handleize(unesc(text)))

# the generator must stay free of the design file and of a browser
gen = open(os.path.join(HERE, 'gen_mega.py')).read()
ck('generator reads taxonomy.json', 'taxonomy.json' in gen)
ck('generator does not read the design handoff HTML', '.dc.html' not in gen)
ck('generator imports no browser', re.search(r'^\s*(import|from)\s+playwright', gen, re.M), None)
ck('the snippet says it is generated', 'Generated by setup/gen_mega.py' in MEGA)

for ok, name, got in res:
    if not ok:
        print(f'FAIL  {name}   (got {got!r})')
print(f'\n{sum(1 for r in res if r[0])}/{len(res)} mega taxonomy checks passed')
sys.exit(0 if all(r[0] for r in res) else 1)
