"""Generate per-category breadcrumb + chips snippets from taxonomy.json.

- snippets/category-breadcrumb.liquid: {% case %} on collection.handle emitting
  the full parent trail (Home / Menu / Group / current).
- snippets/category-chips.liquid: {% case %} emitting the right chip set:
  menu -> its groups (or flat items); group -> its leaf items (or sibling
  groups if empty); leaf -> its siblings. Current chip highlighted dark green
  by snippets/category-chip.liquid.

Sibling sets are shared: one `when 'a' or 'b' …` clause per set, so the file
stays small. Handles reachable from several nav paths keep their first path.
Run from setup/: python3 gen_category_nav.py
"""
import json, re, unicodedata, os, html

HERE = os.path.dirname(os.path.abspath(__file__))
THEME = os.path.join(HERE, '..', 'shopify-theme')

def handleize(s):
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode()
    s = s.lower().replace('&', ' ').replace("'", '')
    return re.sub(r'-{2,}', '-', re.sub(r'[^a-z0-9]+', '-', s)).strip('-')

esc = lambda s: html.escape(s, quote=True)

taxonomy = json.load(open(os.path.join(HERE, 'taxonomy.json')))
PAGES = {'Brands', 'Services'}
menus = [m for m in taxonomy if m['menu'] not in PAGES]

# ---------------------------------------------------------------- breadcrumb
# One when-clause per shared trail. A handle is claimed by its first trail.
claimed = set()
trail_sets = []  # (trail: [(title, handle), ...], members: [handles])

def claim(handles, trail):
    fresh = [h for h in handles if h not in claimed]
    claimed.update(fresh)
    if fresh:
        trail_sets.append((trail, fresh))

for m in menus:
    mh, mt = handleize(m['menu']), m['menu']
    # groups + grouped leaves
    for g in m.get('groups', []):
        gh = handleize(g['title'])
        claim([handleize(i) for i in g['items']], [(mt, mh), (g['title'], gh)])
    claim([handleize(g['title']) for g in m.get('groups', [])], [(mt, mh)])
    claim([handleize(i) for i in m.get('flat', [])], [(mt, mh)])
    # top-level menus themselves fall through to the {% else %} (Home / title)

CRUMB_SEP = '<span>/</span>'
HOME = '<a href="{{ routes.root_url }}" class="hov-green" style="color:#8b9182;">Home</a>'
CUR = '<span style="color:#3a3d39; font-weight:700;">{{ collection.title }}</span>'

def crumb_link(title, handle):
    return f'<a href="/collections/{handle}" class="hov-green" style="color:#8b9182;">{esc(title)}</a>'

lines = ["{% comment %} Generated by setup/gen_category_nav.py — do not edit by hand. "
         "Render with: {% render 'category-breadcrumb', collection: collection %} {% endcomment %}"]
lines.append('{%- case collection.handle -%}')
for trail, members in trail_sets:
    whens = ' or '.join(f"'{h}'" for h in members)
    parts = [HOME] + [crumb_link(t, h) for t, h in trail] + [CUR]
    lines.append(f'{{%- when {whens} -%}}')
    lines.append(CRUMB_SEP.join(parts))
lines.append('{%- else -%}')
lines.append(HOME + CRUMB_SEP + CUR)
lines.append('{%- endcase -%}')
open(os.path.join(THEME, 'snippets', 'category-breadcrumb.liquid'), 'w').write('\n'.join(lines) + '\n')

# ---------------------------------------------------------------- chip sets
# set = (selector handles, chips [(title, handle), ...])
chip_claimed = set()
chip_sets = []

def chip_claim(selectors, chips):
    fresh = [h for h in selectors if h not in chip_claimed]
    chip_claimed.update(fresh)
    if fresh and chips:
        chip_sets.append((fresh, chips))

for m in menus:
    mh = handleize(m['menu'])
    groups = m.get('groups', [])
    flat = m.get('flat', [])
    if groups:
        group_chips = [(g['title'], handleize(g['title'])) for g in groups]
        # menu page shows its groups
        chip_claim([mh], group_chips)
        for g in groups:
            gh = handleize(g['title'])
            item_chips = [(i, handleize(i)) for i in g['items']]
            if item_chips:
                # group page + its leaves share the group's item set
                chip_claim([gh] + [h for _, h in item_chips], item_chips)
            else:
                # empty group (e.g. Self Testing Kits): show sibling groups
                chip_claim([gh], group_chips)
    elif flat:
        flat_chips = [(i, handleize(i)) for i in flat]
        # flat menu + all its leaves share one set
        chip_claim([mh] + [h for _, h in flat_chips], flat_chips)

lines = ["{% comment %} Generated by setup/gen_category_nav.py — do not edit by hand. "
         "Chip sets per category; current chip highlighted by category-chip. "
         "Render with: {% render 'category-chips', collection: collection %} {% endcomment %}"]
lines.append('{%- case collection.handle -%}')
mh_groups = [(g['title'], handleize(g['title'])) for g in next(m for m in menus if m['menu'] == 'Medicines & Health')['groups']]
for selectors, chips in chip_sets:
    whens = ' or '.join(f"'{h}'" for h in selectors)
    lines.append(f'{{%- when {whens} -%}}')
    for title, h in chips:
        lines.append(f"{{% render 'category-chip', h: '{h}', l: '{esc(title)}', cur: collection.handle %}}")
lines.append('{%- else -%}')
for title, h in mh_groups:
    lines.append(f"{{% render 'category-chip', h: '{h}', l: '{esc(title)}', cur: collection.handle %}}")
lines.append('{%- endcase -%}')
open(os.path.join(THEME, 'snippets', 'category-chips.liquid'), 'w').write('\n'.join(lines) + '\n')

# ---------------------------------------------------------------- chip atom
CHIP = """{% comment %} One category chip. Args: h (handle), l (label), cur (current collection handle). {% endcomment %}
{%- if h == cur -%}
<a href="/collections/{{ h }}" aria-current="page" style="flex:0 0 auto; min-width:210px; background:#3f6b4f; color:#ffffff; font-weight:700; font-size:16px; text-align:center; padding:20px 26px; border-radius:9px; display:flex; align-items:center; justify-content:center;">{{ l }}</a>
{%- else -%}
<a href="/collections/{{ h }}" class="hov-bg-green-dk" style="flex:0 0 auto; min-width:210px; background:#82C914; color:#ffffff; font-weight:700; font-size:16px; text-align:center; padding:20px 26px; border-radius:9px; display:flex; align-items:center; justify-content:center;">{{ l }}</a>
{%- endif -%}
"""
open(os.path.join(THEME, 'snippets', 'category-chip.liquid'), 'w').write(CHIP)

# ---------------------------------------------------------------- level lookup
# Outputs the tier of a collection so the template can vary by level — the
# banner drops its image on leaves. Usage:
#   {%- capture cat_level -%}{%- render 'category-level', collection: collection -%}{%- endcapture -%}
by_level = {'menu': [], 'group': [], 'leaf': []}
for m in menus:
    by_level['menu'].append(handleize(m['menu']))
    for g in m.get('groups', []):
        by_level['group'].append(handleize(g['title']))
        by_level['leaf'].extend(handleize(i) for i in g['items'])
    by_level['leaf'].extend(handleize(i) for i in m.get('flat', []))
for extra in ('new-in', 'bundles', 'hot-offers', 'sale'):
    by_level['menu'].append(extra)

# a handle claimed by a higher tier keeps it (a group is never also a leaf)
taken = set()
for tier in ('menu', 'group', 'leaf'):
    uniq = []
    for h in by_level[tier]:
        if h not in taken:
            taken.add(h); uniq.append(h)
    by_level[tier] = sorted(uniq)

brands = [b['handle'] for b in json.load(open(os.path.join(HERE, 'brands.json')))]
brands = sorted(h for h in brands if h not in taken)

lines = ["{% comment %} Generated by setup/gen_category_nav.py — do not edit by hand.",
         "  Outputs the tier of collection: menu | group | leaf | brand (empty if unknown). {% endcomment %}",
         "{%- case collection.handle -%}"]
for tier, handles in (('menu', by_level['menu']), ('group', by_level['group']),
                      ('leaf', by_level['leaf']), ('brand', brands)):
    if not handles:
        continue
    sel = ' or '.join(f"'{h}'" for h in handles)
    lines.append(f"  {{%- when {sel} -%}}{tier}")
lines.append("{%- endcase -%}")
open(os.path.join(THEME, 'snippets', 'category-level.liquid'), 'w').write('\n'.join(lines) + '\n')

n_crumb = sum(len(m) for _, m in trail_sets)
n_chip = sum(len(s) for s, _ in chip_sets)
print(f'breadcrumb: {len(trail_sets)} trail sets covering {n_crumb} handles')
print(f'chips: {len(chip_sets)} chip sets covering {n_chip} handles')
print(f'levels: ' + ', '.join(f'{k} {len(v)}' for k, v in
      (('menu', by_level['menu']), ('group', by_level['group']),
       ('leaf', by_level['leaf']), ('brand', brands))))
for f in ('category-breadcrumb', 'category-chips', 'category-chip', 'category-level'):
    p = os.path.join(THEME, 'snippets', f + '.liquid')
    print(f'{f}.liquid: {os.path.getsize(p)} bytes')
