"""Generate per-category breadcrumb + chips snippets from taxonomy.json.

- snippets/category-breadcrumb.liquid: {% case %} on collection.handle emitting
  the full parent trail (Home / Menu / Group / current).
- snippets/category-chips.liquid: {% case %} emitting the right chip set:
  menu -> its groups (or flat items); group -> its leaf items (or sibling
  groups if empty); leaf -> its siblings. Current chip highlighted dark green
  by snippets/category-chip.liquid.

Sibling sets are shared: one `when 'a' or 'b' …` clause per set, so the file
stays small. Handles reachable from several nav paths keep their first path.
Run from setup/: python3 gen_category_nav.py
"""
import json, re, unicodedata, os, html

HERE = os.path.dirname(os.path.abspath(__file__))
THEME = os.path.join(HERE, '..', 'shopify-theme')

def handleize(s):
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode()
    s = s.lower().replace('&', ' ').replace("'", '')
    return re.sub(r'-{2,}', '-', re.sub(r'[^a-z0-9]+', '-', s)).strip('-')

esc = lambda s: html.escape(s, quote=True)

taxonomy = json.load(open(os.path.join(HERE, 'taxonomy.json')))
PAGES = {'Brands', 'Services'}
menus = [m for m in taxonomy if m['menu'] not in PAGES]

# ---------------------------------------------------------------- breadcrumb
# One when-clause per shared trail. A handle is claimed by its first trail.
claimed = set()
trail_sets = []  # (trail: [(title, handle), ...], members: [handles])

def claim(handles, trail):
    fresh = [h for h in handles if h not in claimed]
    claimed.update(fresh)
    if fresh:
        trail_sets.append((trail, fresh))

for m in menus:
    mh, mt = handleize(m['menu']), m['menu']
    # groups + grouped leaves
    for g in m.get('groups', []):
        gh = handleize(g['title'])
        claim([handleize(i) for i in g['items']], [(mt, mh), (g['title'], gh)])
    claim([handleize(g['title']) for g in m.get('groups', [])], [(mt, mh)])
    claim([handleize(i) for i in m.get('flat', [])], [(mt, mh)])
    # top-level menus themselves fall through to the {% else %} (Home / title)

CRUMB_SEP = '<span>/</span>'
HOME = '<a href="{{ routes.root_url }}" class="hov-green" style="color:#717769;">Home</a>'
CUR = '<span style="color:#3a3d39; font-weight:700;">{{ collection.title }}</span>'

def crumb_link(title, handle):
    return f'<a href="/collections/{handle}" class="hov-green" style="color:#717769;">{esc(title)}</a>'

lines = ["{% comment %} Generated by setup/gen_category_nav.py — do not edit by hand. "
         "Render with: {% render 'category-breadcrumb', collection: collection %} {% endcomment %}"]
lines.append('{%- case collection.handle -%}')
for trail, members in trail_sets:
    whens = ' or '.join(f"'{h}'" for h in members)
    parts = [HOME] + [crumb_link(t, h) for t, h in trail] + [CUR]
    lines.append(f'{{%- when {whens} -%}}')
    lines.append(CRUMB_SEP.join(parts))
lines.append('{%- else -%}')
lines.append(HOME + CRUMB_SEP + CUR)
lines.append('{%- endcase -%}')
open(os.path.join(THEME, 'snippets', 'category-breadcrumb.liquid'), 'w').write('\n'.join(lines) + '\n')

# ------------------------------------------------------- breadcrumb as data
# The snippet above emits anchors, which JSON-LD cannot consume. This emits the
# same trails as "Title~handle|Title~handle" so snippets/structured-data.liquid
# can build a BreadcrumbList without parsing HTML. Same case statement, same
# claim order, so the two can never disagree about a trail.
dlines = ["{% comment %} Generated by setup/gen_category_nav.py — do not edit by hand.",
          "  The breadcrumb trail as data: Title~handle pairs separated by |, excluding",
          "  Home and the current collection. Consumed by snippets/structured-data.liquid.",
          "  Render with: {% render 'category-breadcrumb-data', collection: collection %} {% endcomment %}"]
dlines.append('{%- case collection.handle -%}')
for trail, members in trail_sets:
    whens = ' or '.join(f"'{h}'" for h in members)
    dlines.append(f'{{%- when {whens} -%}}')
    dlines.append('|'.join(f'{t}~{h}' for t, h in trail))
dlines.append('{%- endcase -%}')
open(os.path.join(THEME, 'snippets', 'category-breadcrumb-data.liquid'), 'w').write('\n'.join(dlines) + '\n')

# ------------------------------------------------------------- mobile nav
# The mobile drawer used to be ten flat links with a right-chevron that went
# nowhere but the department page, so 197 groups and leaves were unreachable on
# a phone while the desktop mega menu listed every one of them. This generates
# the drawer's nav as drill-down panels from the same taxonomy the mega menu and
# the breadcrumbs use, so the three cannot disagree.
#
# Depth follows the data: a department with groups drills to a group list, a
# group drills to its leaves, a flat department lists its leaves directly. An
# 18-group department flattened into one panel would be an 88-row scroll.

MNAV_ORDER = ['Medicines & Health', 'Vitamins', 'Beauty', 'Skincare', 'Toiletries',
              'Mother & Baby', 'Fragrance', 'Gifting', 'Sale', 'Brands']
# The nav says "Vitamins & Supplements"; the taxonomy and the handle say "Vitamins".
MNAV_LABEL = {'Vitamins': 'Vitamins & Supplements'}
MNAV_URL = {'Brands': '/pages/brands'}
MNAV_ACCENT = {'Sale'}

CHEVRON = ('<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" '
           'stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'
           '<polyline points="9 6 15 12 9 18"></polyline></svg>')
BACK_ARROW = ('<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" '
              'stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'
              '<polyline points="15 6 9 12 15 18"></polyline></svg>')

def mnav_row(label, url, panel=None, accent=False):
    """One row: always a real link to the category, plus a separate drill button
    where there is something to drill into. Two targets in one row, so tapping
    the name never means 'open a submenu' — that ambiguity is the usual reason
    people cannot reach a parent category on mobile."""
    cls = 'mnav-link mnav-link-accent' if accent else 'mnav-link'
    row = [f'<li class="mnav-row">', f'<a class="{cls}" href="{url}">{esc(label)}</a>']
    if panel:
        row.append(f'<button type="button" class="mnav-more" data-mnav-into="{panel}" '
                   f'aria-label="Browse {esc(label)} categories">{CHEVRON}</button>')
    row.append('</li>')
    return ''.join(row)

def mnav_panel(key, parent, title, url, rows):
    out = [f'<div class="mnav-panel" data-mnav-panel="{key}" data-mnav-parent="{parent}" hidden>']
    out.append(f'<button type="button" class="mnav-back" data-mnav-back>{BACK_ARROW}<span>{esc(title)}</span></button>')
    out.append(f'<a class="mnav-all" href="{url}">Shop all {esc(title)}</a>')
    out.append('<ul class="mnav-list">')
    out.extend(rows)
    out.append('</ul></div>')
    return ''.join(out)

mnav_parts = ["{% comment %} Generated by setup/gen_category_nav.py — do not edit by hand.",
              "  Drill-down panels for the mobile drawer. Driven by theme.js; the drawer shell",
              "  lives in sections/header.liquid.",
              "  Render with: {% render 'mobile-nav' %} {% endcomment %}",
              '<div class="mnav-stack" data-mnav-stack>']

root_rows, sub_panels = [], []
for menu_name in MNAV_ORDER:
    menu = next((m for m in taxonomy if m['menu'] == menu_name), None)
    if menu is None:
        sys.exit(f'mobile nav: unknown menu {menu_name}')
    mh = handleize(menu_name)
    label = MNAV_LABEL.get(menu_name, menu_name)
    url = MNAV_URL.get(menu_name, f'/collections/{mh}')
    groups, flat = menu.get('groups', []), menu.get('flat', [])

    if not groups and not flat:
        root_rows.append(mnav_row(label, url, accent=menu_name in MNAV_ACCENT))
        continue

    root_rows.append(mnav_row(label, url, panel=mh, accent=menu_name in MNAV_ACCENT))

    if groups:
        rows = []
        for g in groups:
            gh = handleize(g['title'])
            items = g.get('items', [])
            rows.append(mnav_row(g['title'], f'/collections/{gh}', panel=gh if items else None))
            if items:
                sub_panels.append(mnav_panel(
                    gh, mh, g['title'], f'/collections/{gh}',
                    [mnav_row(i, f'/collections/{handleize(i)}') for i in items]))
        sub_panels.append(mnav_panel(mh, 'root', label, url, rows))
    else:
        sub_panels.append(mnav_panel(
            mh, 'root', label, url,
            [mnav_row(i, f'/collections/{handleize(i)}') for i in flat]))

mnav_parts.append('<div class="mnav-panel is-current" data-mnav-panel="root">')
mnav_parts.append('<ul class="mnav-list">')
mnav_parts.extend(root_rows)
mnav_parts.append('</ul></div>')
mnav_parts.extend(sub_panels)
mnav_parts.append('</div>')
open(os.path.join(THEME, 'snippets', 'mobile-nav.liquid'), 'w').write('\n'.join(mnav_parts) + '\n')
n_panels = len(sub_panels)
n_dest = sum(part.count('class="mnav-link') for part in mnav_parts)
print(f'mobile-nav: {n_panels} drill-down panels, {n_dest} destinations')

# ---------------------------------------------------------------- chip sets
# set = (selector handles, chips [(title, handle), ...])
chip_claimed = set()
chip_sets = []

def chip_claim(selectors, chips):
    fresh = [h for h in selectors if h not in chip_claimed]
    chip_claimed.update(fresh)
    if fresh and chips:
        chip_sets.append((fresh, chips))

for m in menus:
    mh = handleize(m['menu'])
    groups = m.get('groups', [])
    flat = m.get('flat', [])
    if groups:
        group_chips = [(g['title'], handleize(g['title'])) for g in groups]
        # menu page shows its groups
        chip_claim([mh], group_chips)
        for g in groups:
            gh = handleize(g['title'])
            item_chips = [(i, handleize(i)) for i in g['items']]
            if item_chips:
                # group page + its leaves share the group's item set
                chip_claim([gh] + [h for _, h in item_chips], item_chips)
            else:
                # empty group (e.g. Self Testing Kits): show sibling groups
                chip_claim([gh], group_chips)
    elif flat:
        flat_chips = [(i, handleize(i)) for i in flat]
        # flat menu + all its leaves share one set
        chip_claim([mh] + [h for _, h in flat_chips], flat_chips)

lines = ["{% comment %} Generated by setup/gen_category_nav.py — do not edit by hand. "
         "Chip sets per category; current chip highlighted by category-chip. "
         "Render with: {% render 'category-chips', collection: collection %} {% endcomment %}"]
lines.append('{%- case collection.handle -%}')
mh_groups = [(g['title'], handleize(g['title'])) for g in next(m for m in menus if m['menu'] == 'Medicines & Health')['groups']]
for selectors, chips in chip_sets:
    whens = ' or '.join(f"'{h}'" for h in selectors)
    lines.append(f'{{%- when {whens} -%}}')
    for title, h in chips:
        lines.append(f"{{% render 'category-chip', h: '{h}', l: '{esc(title)}', cur: collection.handle %}}")
lines.append('{%- else -%}')
for title, h in mh_groups:
    lines.append(f"{{% render 'category-chip', h: '{h}', l: '{esc(title)}', cur: collection.handle %}}")
lines.append('{%- endcase -%}')
open(os.path.join(THEME, 'snippets', 'category-chips.liquid'), 'w').write('\n'.join(lines) + '\n')

# ---------------------------------------------------------------- chip atom
CHIP = """{% comment %} One category chip. Args: h (handle), l (label), cur (current collection handle). {% endcomment %}
{%- if h == cur -%}
<a href="/collections/{{ h }}" aria-current="page" style="flex:0 0 auto; min-width:210px; background:var(--c-dark); color:var(--c-on-dark); font-weight:700; font-size:16px; text-align:center; padding:20px 26px; border-radius:9px; display:flex; align-items:center; justify-content:center;">{{ l }}</a>
{%- else -%}
<a href="/collections/{{ h }}" class="hov-bg-green-dk" style="flex:0 0 auto; min-width:210px; background:var(--c-primary); color:var(--c-on-primary); font-weight:700; font-size:16px; text-align:center; padding:20px 26px; border-radius:9px; display:flex; align-items:center; justify-content:center;">{{ l }}</a>
{%- endif -%}
"""
open(os.path.join(THEME, 'snippets', 'category-chip.liquid'), 'w').write(CHIP)

# ---------------------------------------------------------------- level lookup
# Outputs the tier of a collection so the template can vary by level — the
# banner drops its image on leaves. Usage:
#   {%- capture cat_level -%}{%- render 'category-level', collection: collection -%}{%- endcapture -%}
by_level = {'menu': [], 'group': [], 'leaf': []}
for m in menus:
    by_level['menu'].append(handleize(m['menu']))
    for g in m.get('groups', []):
        by_level['group'].append(handleize(g['title']))
        by_level['leaf'].extend(handleize(i) for i in g['items'])
    by_level['leaf'].extend(handleize(i) for i in m.get('flat', []))
for extra in ('new-in', 'bundles', 'hot-offers', 'sale'):
    by_level['menu'].append(extra)

# a handle claimed by a higher tier keeps it (a group is never also a leaf)
taken = set()
for tier in ('menu', 'group', 'leaf'):
    uniq = []
    for h in by_level[tier]:
        if h not in taken:
            taken.add(h); uniq.append(h)
    by_level[tier] = sorted(uniq)

brands = [b['handle'] for b in json.load(open(os.path.join(HERE, 'brands.json')))]
brands = sorted(h for h in brands if h not in taken)

lines = ["{% comment %} Generated by setup/gen_category_nav.py — do not edit by hand.",
         "  Outputs the tier of collection: menu | group | leaf | brand (empty if unknown). {% endcomment %}",
         "{%- case collection.handle -%}"]
for tier, handles in (('menu', by_level['menu']), ('group', by_level['group']),
                      ('leaf', by_level['leaf']), ('brand', brands)):
    if not handles:
        continue
    sel = ' or '.join(f"'{h}'" for h in handles)
    lines.append(f"  {{%- when {sel} -%}}{tier}")
lines.append("{%- endcase -%}")
open(os.path.join(THEME, 'snippets', 'category-level.liquid'), 'w').write('\n'.join(lines) + '\n')

# ------------------------------------------------------- collection specificity
# Which of a product's collections should the PDP breadcrumb use? Shopify's
# product.collections ordering is arbitrary, so a product in both Vitamins and
# Skin, Hair & Nails could breadcrumb to either. Rank them and take the most
# specific: both parents are true, but the leaf tells the visitor more.
#
#   brand           1   a facet, not a taxonomy parent. Last resort.
#   menu    (d1)    2
#   group   (d2)    4
#   leaf    (d2)    5   terminal, so more specific than a group at the same depth
#   leaf    (d3)    7
#
# Emitted as a number so the caller compares with plain arithmetic and needs no
# knowledge of the taxonomy.
depth_of = {}
for trail, members in trail_sets:
    for h in members:
        depth_of[h] = len(trail) + 1

leaves = set(by_level['leaf'])
rank_of = {}
for tier in ('menu', 'group', 'leaf'):
    for h in by_level[tier]:
        d = depth_of.get(h, 1)
        rank_of[h] = d * 2 + (1 if h in leaves else 0)
for h in brands:
    rank_of[h] = 1

by_rank = {}
for h, r in rank_of.items():
    by_rank.setdefault(r, []).append(h)

lines = ["{% comment %} Generated by setup/gen_category_nav.py — do not edit by hand.",
         "  How specific a collection is, as a number. Higher is more specific; 0 is unknown.",
         "  Used by snippets/product-primary-collection.liquid to choose a PDP breadcrumb",
         "  parent, because Shopify's product.collections ordering is arbitrary.",
         "  Render with: {% render 'collection-rank', handle: c.handle %} {% endcomment %}",
         "{%- case handle -%}"]
for r in sorted(by_rank, reverse=True):
    sel = ' or '.join(f"'{h}'" for h in sorted(by_rank[r]))
    lines.append(f"  {{%- when {sel} -%}}{r}")
lines.append("  {%- else -%}0")
lines.append("{%- endcase -%}")
open(os.path.join(THEME, 'snippets', 'collection-rank.liquid'), 'w').write('\n'.join(lines) + '\n')

n_crumb = sum(len(m) for _, m in trail_sets)
n_chip = sum(len(s) for s, _ in chip_sets)
print(f'breadcrumb: {len(trail_sets)} trail sets covering {n_crumb} handles')
print(f'chips: {len(chip_sets)} chip sets covering {n_chip} handles')
print(f'levels: ' + ', '.join(f'{k} {len(v)}' for k, v in
      (('menu', by_level['menu']), ('group', by_level['group']),
       ('leaf', by_level['leaf']), ('brand', brands))))
for f in ('category-breadcrumb', 'category-breadcrumb-data', 'category-chips', 'category-chip', 'category-level', 'collection-rank'):
    p = os.path.join(THEME, 'snippets', f + '.liquid')
    print(f'{f}.liquid: {os.path.getsize(p)} bytes')
