"""brands.json -> snippets/brand-az.liquid (A–Z brand index, every brand linked
to its own brand collection page). Letter groups carry anchor ids so the A–Z
chips can jump to them. Run from setup/: python3 gen_brands.py"""
import json, os, html
from collections import OrderedDict

HERE = os.path.dirname(os.path.abspath(__file__))
THEME = os.path.join(HERE, '..', 'shopify-theme')

brands = json.load(open(os.path.join(HERE, 'brands.json')))
by_letter = OrderedDict()
for b in brands:
    by_letter.setdefault(b['letter'], []).append(b)

esc = lambda s: html.escape(s, quote=True)
# markup mirrors the design's A–Z grid children; ids let the letter chips jump here
out = ["{% comment %} Generated by setup/gen_brands.py — do not edit by hand. Renders the A–Z grid children. {% endcomment %}"]
for letter, items in by_letter.items():
    out.append(f'<div id="brand-{letter.lower()}" style="scroll-margin-top:130px;">')
    out.append(f'  <div style="font-family:\'Arial Rounded MT Bold\', Arial, sans-serif; font-weight:800; font-size:22px; color:#92C83F; padding-bottom:8px; margin-bottom:10px; border-bottom:2px solid #eef2e8;">{letter}</div>')
    out.append('  <div style="display:flex; flex-direction:column; gap:8px;">')
    for b in items:
        # CeraVe also opens the in-page brand-detail demo view; the href is the no-JS fallback
        demo = ' data-view-btn="brand"' if b['display'] == 'CeraVe' else ''
        out.append(f'    <a href="/collections/{b["handle"]}"{demo} class="brand-az-a">{esc(b["display"])}</a>')
    out.append('  </div>')
    out.append('</div>')

path = os.path.join(THEME, 'snippets', 'brand-az.liquid')
open(path, 'w').write('\n'.join(out) + '\n')
print(f'wrote {os.path.relpath(path, THEME)}: {len(brands)} brands, {len(by_letter)} letters')
